### ISSUE TITLE
Can't compile hawaii/shell

### ISSUE THREAD

**Issue by delleceste** [hawaii-desktop/hawaii-manifest#11]
Good morning.

I am trying to compile shell under hawaii:

git checkout stable
Switched to branch 'stable'
Your branch is up-to-date with 'origin/stable'.

/home/giacomo/Descargas/hawaii/shell/src/client/hawaiishell.cpp: In lambda function:
/home/giacomo/Descargas/hawaii/shell/src/client/hawaiishell.cpp:347:31: error: 'this' was not captured for this lambda function
(solved including 'this' in capture)

BUT:

Scanning dependencies of target hawaii-shell
[ 56%] Building CXX object src/compositor/CMakeFiles/hawaii-shell.dir/main.cpp.o
[ 57%] Building CXX object src/compositor/CMakeFiles/hawaii-shell.dir/compositor.cpp.o
/home/giacomo/Descargas/hawaii/shell/src/compositor/compositor.cpp: In member function 'void Compositor::frameSwapped()':
/home/giacomo/Descargas/hawaii/shell/src/compositor/compositor.cpp:284:19: error: 'frameFinished' was not declared in this scope
In file included from /usr/local/qt5/include/QtCore/qiodevice.h:47:0,
                 from /usr/local/qt5/include/QtCore/qtextstream.h:45,
                 from /usr/local/qt5/include/QtCore/qdebug.h:50,
                 from /usr/local/qt5/include/QtCore/QDebug:1,
                 from /home/giacomo/Descargas/hawaii/shell/src/compositor/compositor.cpp:27:
/usr/local/qt5/include/QtCore/qobject.h: In instantiation of 'static typename QtPrivate::QEnableIf<(QtPrivate::FunctionPointer<Func2>::ArgumentCount == (-1)), QMetaObject::Connection>::Type QObject::connect(const typename QtPrivate::FunctionPointer<Func>::Object*, Func1, const QObject*, Func2, Qt::ConnectionType) [with Func1 = void (QWaylandSurface::*)(const QRegion&); Func2 = Compositor::setCursorSurface(QWaylandSurface*, int, int)::<lambda(const QRect&)>; typename QtPrivate::QEnableIf<(QtPrivate::FunctionPointer<Func2>::ArgumentCount == (-1)), QMetaObject::Connection>::Type = QMetaObject::Connection; typename QtPrivate::FunctionPointer<Func>::Object = QWaylandSurface; QObject = QObject]':
/usr/local/qt5/include/QtCore/qobject.h:289:74:   required from 'static typename QtPrivate::QEnableIf<(QtPrivate::FunctionPointer<Func2>::ArgumentCount == (-1)), QMetaObject::Connection>::Type QObject::connect(const typename QtPrivate::FunctionPointer<Func>::Object*, Func1, Func2) [with Func1 = void (QWaylandSurface::*)(const QRegion&); Func2 = Compositor::setCursorSurface(QWaylandSurface*, int, int)::<lambda(const QRect&)>; typename QtPrivate::QEnableIf<(QtPrivate::FunctionPointer<Func2>::ArgumentCount == (-1)), QMetaObject::Connection>::Type = QMetaObject::Connection; typename QtPrivate::FunctionPointer<Func>::Object = QWaylandSurface]'
/home/giacomo/Descargas/hawaii/shell/src/compositor/compositor.cpp:396:10:   required from here
/usr/local/qt5/include/QtCore/qobject.h:300:122: warning: overflow in implicit constant conversion [-Woverflow]
/usr/local/qt5/include/QtCore/qobject.h:302:9: error: static assertion failed: Signal and slot arguments are not compatible.
In file included from /usr/local/qt5/include/QtCore/qobjectdefs.h:51:0,
                 from /usr/local/qt5/include/QtCore/qobject.h:48,
                 from /usr/local/qt5/include/QtCore/qiodevice.h:47,
                 from /usr/local/qt5/include/QtCore/qtextstream.h:45,
                 from /usr/local/qt5/include/QtCore/qdebug.h:50,
                 from /usr/local/qt5/include/QtCore/QDebug:1,
                 from /home/giacomo/Descargas/hawaii/shell/src/compositor/compositor.cpp:27:
/usr/local/qt5/include/QtCore/qobjectdefs_impl.h: In instantiation of 'struct QtPrivate::FunctorReturnType<Compositor::setCursorSurface(QWaylandSurface*, int, int)::<lambda(const QRect&)>, QtPrivate::List<> >':
/usr/local/qt5/include/QtCore/qobject.h:305:158:   required from 'static typename QtPrivate::QEnableIf<(QtPrivate::FunctionPointer<Func2>::ArgumentCount == (-1)), QMetaObject::Connection>::Type QObject::connect(const typename QtPrivate::FunctionPointer<Func>::Object*, Func1, const QObject*, Func2, Qt::ConnectionType) [with Func1 = void (QWaylandSurface::*)(const QRegion&); Func2 = Compositor::setCursorSurface(QWaylandSurface*, int, int)::<lambda(const QRect&)>; typename QtPrivate::QEnableIf<(QtPrivate::FunctionPointer<Func2>::ArgumentCount == (-1)), QMetaObject::Connection>::Type = QMetaObject::Connection; typename QtPrivate::FunctionPointer<Func>::Object = QWaylandSurface; QObject = QObject]'
/usr/local/qt5/include/QtCore/qobject.h:289:74:   required from 'static typename QtPrivate::QEnableIf<(QtPrivate::FunctionPointer<Func2>::ArgumentCount == (-1)), QMetaObject::Connection>::Type QObject::connect(const typename QtPrivate::FunctionPointer<Func>::Object*, Func1, Func2) [with Func1 = void (QWaylandSurface::*)(const QRegion&); Func2 = Compositor::setCursorSurface(QWaylandSurface*, int, int)::<lambda(const QRect&)>; typename QtPrivate::QEnableIf<(QtPrivate::FunctionPointer<Func2>::ArgumentCount == (-1)), QMetaObject::Connection>::Type = QMetaObject::Connection; typename QtPrivate::FunctionPointer<Func>::Object = QWaylandSurface]'
/home/giacomo/Descargas/hawaii/shell/src/compositor/compositor.cpp:396:10:   required from here
/usr/local/qt5/include/QtCore/qobjectdefs_impl.h:633:78: error: no matching function for call to 'Compositor::setCursorSurface(QWaylandSurface*, int, int)::<lambda(const QRect&)>::operator()()'
/usr/local/qt5/include/QtCore/qobjectdefs_impl.h:633:78: note: candidate is:
/home/giacomo/Descargas/hawaii/shell/src/compositor/compositor.cpp:383:74: note: Compositor::setCursorSurface(QWaylandSurface*, int, int)::<lambda(const QRect&)>
/home/giacomo/Descargas/hawaii/shell/src/compositor/compositor.cpp:383:74: note:   candidate expects 1 argument, 0 provided
In file included from /usr/local/qt5/include/QtCore/qobject.h:58:0,
                 from /usr/local/qt5/include/QtCore/qiodevice.h:47,
                 from /usr/local/qt5/include/QtCore/qtextstream.h:45,
                 from /usr/local/qt5/include/QtCore/qdebug.h:50,
                 from /usr/local/qt5/include/QtCore/QDebug:1,
                 from /home/giacomo/Descargas/hawaii/shell/src/compositor/compositor.cpp:27:
/usr/local/qt5/include/QtCore/qobject_impl.h: At global scope:
/usr/local/qt5/include/QtCore/qobject_impl.h:209:18: error: 'QtPrivate::QFunctorSlotObject<Func, N, Args, R>::QFunctorSlotObject(const Func&) [with Func = Compositor::setCursorSurface(QWaylandSurface*, int, int)::<lambda(const QRect&)>; int N = 0; Args = QtPrivate::List<>; R = void]', declared using local type 'const Compositor::setCursorSurface(QWaylandSurface*, int, int)::<lambda(const QRect&)>', is used but never defined [-fpermissive]
src/compositor/CMakeFiles/hawaii-shell.dir/build.make:171: recipe for target 'src/compositor/CMakeFiles/hawaii-shell.dir/compositor.cpp.o' failed
make[2]: *** [src/compositor/CMakeFiles/hawaii-shell.dir/compositor.cpp.o] Error 1
CMakeFiles/Makefile2:320: recipe for target 'src/compositor/CMakeFiles/hawaii-shell.dir/all' failed
make[1]: *** [src/compositor/CMakeFiles/hawaii-shell.dir/all] Error 2
Makefile:136: recipe for target 'all' failed
make: *** [all] Error 2

woody shell # git checkout dev
warning: unable to rmdir 3rdparty/libqtxdg: Directory not empty
Switched to branch 'dev'
Your branch is up-to-date with 'origin/dev'.

woody shell # git clean -f -d -x

woody shell # cmake -DQTWAYLAND_SCANNER_EXECUTABLE=/usr/local/qt5/bin/qtwaylandscanner -DCMAKE_PREFIX_PATH=/usr/local/qt5:/usr/local/qt5/plugins:/usr/local/lib/cmake/PolkitQt-1:.  -DCMAKE_INCLUDE_PATH=/usr/local/qt5/include -DCMAKE_PREFIX_PATH=/usr/local/qt5:/usr/local/qt5/lib
-- The C compiler identification is GNU 4.7.3
-- The CXX compiler identification is GNU 4.7.3
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found PkgConfig: /usr/bin/pkg-config (found suitable version "0.28", minimum required is "0.22") 
-- checking for module 'wayland-client'
--   found wayland-client, version 1.4.0
-- checking for module 'wayland-server'
--   found wayland-server, version 1.4.0
-- checking for module 'pixman-1'
--   found pixman-1, version 0.32.4
-- checking for module 'weston'
--   found weston, version 1.4.0
-- checking for module 'libsystemd-daemon'
--   found libsystemd-daemon, version 212
-- Found ALSA: /usr/lib64/libasound.so (found version "1.0.27.2") 
CMake Error at src/packages/backgrounds/CMakeLists.txt:1 (hawaiishell_install_package):
  Unknown CMake command "hawaiishell_install_package".

-- Configuring incomplete, errors occurred!

Could you please tell me if I am using not compatible versions?
Is it possible to fix it?

Thanks.

Giacomo 

Gentoo ~amd64

**Comment by plfiorini** [comment]
It likely doesn't apply anymore, closing
